
# configuration.yaml

sensor:
  - platform: rest
    name: RescueTime Daily Summary
    resource: "https://www.rescuetime.com/anapi/daily_summary_feed?key=YOUR_API_KEY"
    method: GET
    scan_interval: 86400  # Fetch data once per day
    value_template: "{{ value_json[0]['productivity_pulse'] if value_json[0]['date'] == (now().date() - timedelta(days=1)).strftime('%Y-%m-%d') else 'No data' }}"
    json_attributes:
      - date
      - productivity_pulse
      - very_productive_percentage
      - productive_percentage
      - neutral_percentage
      - distracting_percentage
      - very_distracting_percentage
      - all_productive_percentage
      - all_distracting_percentage
      - uncategorized_percentage
      - business_percentage
      - communication_and_scheduling_percentage
      - social_networking_percentage
      - design_and_composition_percentage
      - entertainment_percentage
      - news_percentage
      - software_development_percentage
      - reference_and_learning_percentage
      - shopping_percentage
      - utilities_percentage
      - total_hours
      - very_productive_hours
      - productive_hours
      - neutral_hours
      - distracting_hours
      - very_distracting_hours
      - all_productive_hours
      - all_distracting_hours
      - uncategorized_hours
      - business_hours
      - communication_and_scheduling_hours
      - social_networking_hours
      - design_and_composition_hours
      - entertainment_hours
      - news_hours
      - software_development_hours
      - reference_and_learning_hours
      - shopping_hours
      - utilities_hours

template:
  - sensor:

      - name: RescueTime Yesterday Productivity Pulse
        state: "{{ state_attr('sensor.rescuetime_daily_summary', 'productivity_pulse') }}"
        unit_of_measurement: "Pulse"
        device_class: measurement
    
      - name: RescueTime Yesterday Very Productive Percentage
        state: "{{ state_attr('sensor.rescuetime_daily_summary', 'very_productive_percentage') }}"
        unit_of_measurement: "%"
        device_class: measurement
    
      - name: RescueTime Yesterday Productive Percentage
        state: "{{ state_attr('sensor.rescuetime_daily_summary', 'productive_percentage') }}"
        unit_of_measurement: "%"
        device_class: measurement
    
      - name: RescueTime Yesterday Neutral Percentage
        state: "{{ state_attr('sensor.rescuetime_daily_summary', 'neutral_percentage') }}"
        unit_of_measurement: "%"
        device_class: measurement
    
      - name: RescueTime Yesterday Distracting Percentage
        state: "{{ state_attr('sensor.rescuetime_daily_summary', 'distracting_percentage') }}"
        unit_of_measurement: "%"
        device_class: measurement
    
      - name: RescueTime Yesterday Very Distracting Percentage
        state: "{{ state_attr('sensor.rescuetime_daily_summary', 'very_distracting_percentage') }}"
        unit_of_measurement: "%"
        device_class: measurement
    
      - name: RescueTime Yesterday All Productive Percentage
        state: "{{ state_attr('sensor.rescuetime_daily_summary', 'all_productive_percentage') }}"
        unit_of_measurement: "%"
        device_class: measurement
    
      - name: RescueTime Yesterday All Distracting Percentage
        state: "{{ state_attr('sensor.rescuetime_daily_summary', 'all_distracting_percentage') }}"
        unit_of_measurement: "%"
        device_class: measurement
    
      - name: RescueTime Yesterday Uncategorized Percentage
        state: "{{ state_attr('sensor.rescuetime_daily_summary', 'uncategorized_percentage') }}"
        unit_of_measurement: "%"
        device_class: measurement
    
      - name: RescueTime Yesterday Business Percentage
        state: "{{ state_attr('sensor.rescuetime_daily_summary', 'business_percentage') }}"
        unit_of_measurement: "%"
        device_class: measurement
    
      - name: RescueTime Yesterday Communication And Scheduling Percentage
        state: "{{ state_attr('sensor.rescuetime_daily_summary', 'communication_and_scheduling_percentage') }}"
        unit_of_measurement: "%"
        device_class: measurement
    
      - name: RescueTime Yesterday Social Networking Percentage
        state: "{{ state_attr('sensor.rescuetime_daily_summary', 'social_networking_percentage') }}"
        unit_of_measurement: "%"
        device_class: measurement
    
      - name: RescueTime Yesterday Design And Composition Percentage
        state: "{{ state_attr('sensor.rescuetime_daily_summary', 'design_and_composition_percentage') }}"
        unit_of_measurement: "%"
        device_class: measurement
    
      - name: RescueTime Yesterday Entertainment Percentage
        state: "{{ state_attr('sensor.rescuetime_daily_summary', 'entertainment_percentage') }}"
        unit_of_measurement: "%"
        device_class: measurement
    
      - name: RescueTime Yesterday News Percentage
        state: "{{ state_attr('sensor.rescuetime_daily_summary', 'news_percentage') }}"
        unit_of_measurement: "%"
        device_class: measurement
    
      - name: RescueTime Yesterday Software Development Percentage
        state: "{{ state_attr('sensor.rescuetime_daily_summary', 'software_development_percentage') }}"
        unit_of_measurement: "%"
        device_class: measurement
    
      - name: RescueTime Yesterday Reference And Learning Percentage
        state: "{{ state_attr('sensor.rescuetime_daily_summary', 'reference_and_learning_percentage') }}"
        unit_of_measurement: "%"
        device_class: measurement
    
      - name: RescueTime Yesterday Shopping Percentage
        state: "{{ state_attr('sensor.rescuetime_daily_summary', 'shopping_percentage') }}"
        unit_of_measurement: "%"
        device_class: measurement
    
      - name: RescueTime Yesterday Utilities Percentage
        state: "{{ state_attr('sensor.rescuetime_daily_summary', 'utilities_percentage') }}"
        unit_of_measurement: "%"
        device_class: measurement
    
      - name: RescueTime Yesterday Total Hours
        state: "{{ state_attr('sensor.rescuetime_daily_summary', 'total_hours') }}"
        unit_of_measurement: "hours"
        device_class: duration
    
      - name: RescueTime Yesterday Very Productive Hours
        state: "{{ state_attr('sensor.rescuetime_daily_summary', 'very_productive_hours') }}"
        unit_of_measurement: "hours"
        device_class: duration
    
      - name: RescueTime Yesterday Productive Hours
        state: "{{ state_attr('sensor.rescuetime_daily_summary', 'productive_hours') }}"
        unit_of_measurement: "hours"
        device_class: duration
    
      - name: RescueTime Yesterday Neutral Hours
        state: "{{ state_attr('sensor.rescuetime_daily_summary', 'neutral_hours') }}"
        unit_of_measurement: "hours"
        device_class: duration
    
      - name: RescueTime Yesterday Distracting Hours
        state: "{{ state_attr('sensor.rescuetime_daily_summary', 'distracting_hours') }}"
        unit_of_measurement: "hours"
        device_class: duration
    
      - name: RescueTime Yesterday Very Distracting Hours
        state: "{{ state_attr('sensor.rescuetime_daily_summary', 'very_distracting_hours') }}"
        unit_of_measurement: "hours"
        device_class: duration
    
      - name: RescueTime Yesterday All Productive Hours
        state: "{{ state_attr('sensor.rescuetime_daily_summary', 'all_productive_hours') }}"
        unit_of_measurement: "hours"
        device_class: duration
    
      - name: RescueTime Yesterday All Distracting Hours
        state: "{{ state_attr('sensor.rescuetime_daily_summary', 'all_distracting_hours') }}"
        unit_of_measurement: "hours"
        device_class: duration
    
      - name: RescueTime Yesterday Uncategorized Hours
        state: "{{ state_attr('sensor.rescuetime_daily_summary', 'uncategorized_hours') }}"
        unit_of_measurement: "hours"
        device_class: duration
    
      - name: RescueTime Yesterday Business Hours
        state: "{{ state_attr('sensor.rescuetime_daily_summary', 'business_hours') }}"
        unit_of_measurement: "hours"
        device_class: duration
    
      - name: RescueTime Yesterday Communication And Scheduling Hours
        state: "{{ state_attr('sensor.rescuetime_daily_summary', 'communication_and_scheduling_hours') }}"
        unit_of_measurement: "hours"
        device_class: duration
    
      - name: RescueTime Yesterday Social Networking Hours
        state: "{{ state_attr('sensor.rescuetime_daily_summary', 'social_networking_hours') }}"
        unit_of_measurement: "hours"
        device_class: duration
    
      - name: RescueTime Yesterday Design And Composition Hours
        state: "{{ state_attr('sensor.rescuetime_daily_summary', 'design_and_composition_hours') }}"
        unit_of_measurement: "hours"
        device_class: duration
    
      - name: RescueTime Yesterday Entertainment Hours
        state: "{{ state_attr('sensor.rescuetime_daily_summary', 'entertainment_hours') }}"
        unit_of_measurement: "hours"
        device_class: duration
    
      - name: RescueTime Yesterday News Hours
        state: "{{ state_attr('sensor.rescuetime_daily_summary', 'news_hours') }}"
        unit_of_measurement: "hours"
        device_class: duration
    
      - name: RescueTime Yesterday Software Development Hours
        state: "{{ state_attr('sensor.rescuetime_daily_summary', 'software_development_hours') }}"
        unit_of_measurement: "hours"
        device_class: duration
    
      - name: RescueTime Yesterday Reference And Learning Hours
        state: "{{ state_attr('sensor.rescuetime_daily_summary', 'reference_and_learning_hours') }}"
        unit_of_measurement: "hours"
        device_class: duration
    
      - name: RescueTime Yesterday Shopping Hours
        state: "{{ state_attr('sensor.rescuetime_daily_summary', 'shopping_hours') }}"
        unit_of_measurement: "hours"
        device_class: duration
    
      - name: RescueTime Yesterday Utilities Hours
        state: "{{ state_attr('sensor.rescuetime_daily_summary', 'utilities_hours') }}"
        unit_of_measurement: "hours"
        device_class: duration
    
