sensor:
  - platform: rest
    name: RescueTime Data
    resource: "https://www.rescuetime.com/anapi/daily_summary_feed?key={{ secrets.rescuetime_api_key }}"
    scan_interval: 3600
    value_template: "{{ value_json[0].date }}"
    json_attributes:
      - productivity_pulse
      - very_productive_percentage
      - productive_percentage
      - neutral_percentage
      - distracting_percentage
      - very_distracting_percentage
      - all_productive_percentage
      - all_distracting_percentage
      - uncategorized_percentage
      - business_percentage
      - communication_and_scheduling_percentage
      - social_networking_percentage
      - design_and_composition_percentage
      - entertainment_percentage
      - news_percentage
      - software_development_percentage
      - reference_and_learning_percentage
      - shopping_percentage
      - utilities_percentage
      - total_hours
      - very_productive_hours
      - productive_hours
      - neutral_hours
      - distracting_hours
      - very_distracting_hours
      - all_productive_hours
      - all_distracting_hours
      - uncategorized_hours
      - business_hours
      - communication_and_scheduling_hours
      - social_networking_hours
      - design_and_composition_hours
      - entertainment_hours
      - news_hours
      - software_development_hours
      - reference_and_learning_hours
      - shopping_hours
      - utilities_hours

  - platform: template
    sensors:
      productivity_pulse:
        friendly_name: "Productivity Pulse"
        value_template: "{{ state_attr('sensor.rescuetime_data', 'productivity_pulse') }}"
        unit_of_measurement: "%"

      very_productive_percentage:
        friendly_name: "Very Productive Percentage"
        value_template: "{{ state_attr('sensor.rescuetime_data', 'very_productive_percentage') }}"
        unit_of_measurement: "%"

      productive_percentage:
        friendly_name: "Productive Percentage"
        value_template: "{{ state_attr('sensor.rescuetime_data', 'productive_percentage') }}"
        unit_of_measurement: "%"

      neutral_percentage:
        friendly_name: "Neutral Percentage"
        value_template: "{{ state_attr('sensor.rescuetime_data', 'neutral_percentage') }}"
        unit_of_measurement: "%"

      distracting_percentage:
        friendly_name: "Distracting Percentage"
        value_template: "{{ state_attr('sensor.rescuetime_data', 'distracting_percentage') }}"
        unit_of_measurement: "%"

      very_distracting_percentage:
        friendly_name: "Very Distracting Percentage"
        value_template: "{{ state_attr('sensor.rescuetime_data', 'very_distracting_percentage') }}"
        unit_of_measurement: "%"

      all_productive_percentage:
        friendly_name: "All Productive Percentage"
        value_template: "{{ state_attr('sensor.rescuetime_data', 'all_productive_percentage') }}"
        unit_of_measurement: "%"

      all_distracting_percentage:
        friendly_name: "All Distracting Percentage"
        value_template: "{{ state_attr('sensor.rescuetime_data', 'all_distracting_percentage') }}"
        unit_of_measurement: "%"

      total_hours:
        friendly_name: "Total Hours"
        value_template: "{{ state_attr('sensor.rescuetime_data', 'total_hours') }}"
        unit_of_measurement: "hours"

      very_productive_hours:
        friendly_name: "Very Productive Hours"
        value_template: "{{ state_attr('sensor.rescuetime_data', 'very_productive_hours') }}"
        unit_of_measurement: "hours"

      productive_hours:
        friendly_name: "Productive Hours"
        value_template: "{{ state_attr('sensor.rescuetime_data', 'productive_hours') }}"
        unit_of_measurement: "hours"

      neutral_hours:
        friendly_name: "Neutral Hours"
        value_template: "{{ state_attr('sensor.rescuetime_data', 'neutral_hours') }}"
        unit_of_measurement: "hours"

      distracting_hours:
        friendly_name: "Distracting Hours"
        value_template: "{{ state_attr('sensor.rescuetime_data', 'distracting_hours') }}"
        unit_of_measurement: "hours"

      very_distracting_hours:
        friendly_name: "Very Distracting Hours"
        value_template: "{{ state_attr('sensor.rescuetime_data', 'very_distracting_hours') }}"
        unit_of_measurement: "hours"

      entertainment_percentage:
        friendly_name: "Entertainment Percentage"
        value_template: "{{ state_attr('sensor.rescuetime_data', 'entertainment_percentage') }}"
        unit_of_measurement: "%"

      business_hours:
        friendly_name: "Business Hours"
        value_template: "{{ state_attr('sensor.rescuetime_data', 'business_hours') }}"
        unit_of_measurement: "hours"

      shopping_hours:
        friendly_name: "Shopping Hours"
        value_template: "{{ state_attr('sensor.rescuetime_data', 'shopping_hours') }}"
        unit_of_measurement: "hours"

      utilities_hours:
        friendly_name: "Utilities Hours"
        value_template: "{{ state_attr('sensor.rescuetime_data', 'utilities_hours') }}"
        unit_of_measurement: "hours"
